backend:
  name: github
  repo: Pune-Animal-Liberation/pal-website
  branch: main
  base_url: https://cms-oauth.pravin-chaudhary.workers.dev
  auth_endpoint: auth

publish_mode: editorial_workflow

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
